package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1


/**
 * ActionTypes generated by hbm2java
 */
public enum ActionType{
	ADD_BOOK(0),ADD_COMMENT(1);
	
	private int actionTypeCode;
	 
	private ActionType(int actionTypeCode) {
		this.actionTypeCode = actionTypeCode;
	}
 
	public int asCode() {
		return this.actionTypeCode;
	}
	
}