package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1


/**
 * ActionTypes generated by hbm2java
 */
public class ActionTypes implements java.io.Serializable {

	private Integer actionId;
	private String actionDesc;

	public ActionTypes() {
	}

	public ActionTypes(String actionDesc) {
		this.actionDesc = actionDesc;
	}

	public Integer getActionId() {
		return this.actionId;
	}

	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

	public String getActionDesc() {
		return this.actionDesc;
	}

	public void setActionDesc(String actionDesc) {
		this.actionDesc = actionDesc;
	}

}
