package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BookLike generated by hbm2java
 */
public class BookLike implements java.io.Serializable {

	private Integer bookLikeId;
	private Integer bookLikerId;
	private Integer bookId;
	private Date bookLikeDate;

	public BookLike() {
	}

	public BookLike(Integer bookLikerId, Integer bookId, Date bookLikeDate) {
		this.bookLikerId = bookLikerId;
		this.bookId = bookId;
		this.bookLikeDate = bookLikeDate;
	}

	public Integer getBookLikeId() {
		return this.bookLikeId;
	}

	public void setBookLikeId(Integer bookLikeId) {
		this.bookLikeId = bookLikeId;
	}

	public Integer getBookLikerId() {
		return this.bookLikerId;
	}

	public void setBookLikerId(Integer bookLikerId) {
		this.bookLikerId = bookLikerId;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public Date getBookLikeDate() {
		return this.bookLikeDate;
	}

	public void setBookLikeDate(Date bookLikeDate) {
		this.bookLikeDate = bookLikeDate;
	}

}
