package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BookLike generated by hbm2java
 */
public class BookLike implements java.io.Serializable {

	private Long bookLikeId;
	private Long bookLikerId;
	private Long bookId;
	private Date bookLikeDate;

	public BookLike() {
	}

	public BookLike(Long bookLikerId, Long bookId, Date bookLikeDate) {
		this.bookLikerId = bookLikerId;
		this.bookId = bookId;
		this.bookLikeDate = bookLikeDate;
	}

	public Long getBookLikeId() {
		return this.bookLikeId;
	}

	public void setBookLikeId(Long bookLikeId) {
		this.bookLikeId = bookLikeId;
	}

	public Long getBookLikerId() {
		return this.bookLikerId;
	}

	public void setBookLikerId(Long bookLikerId) {
		this.bookLikerId = bookLikerId;
	}

	public Long getBookId() {
		return this.bookId;
	}

	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}

	public Date getBookLikeDate() {
		return this.bookLikeDate;
	}

	public void setBookLikeDate(Date bookLikeDate) {
		this.bookLikeDate = bookLikeDate;
	}

}
