package com.bookworm.model;

import java.util.Date;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * FollowShip generated by hbm2java
 */
public class Followship implements java.io.Serializable {

	private Long followerUserId;
	private Long followedUserId;
	private Date creationDate;
	private Long followshipId;

	public Followship() {
	}

	public Followship(Long followerUserId) {
		this.followerUserId = followerUserId;
	}

	public Followship(Long followerUserId, Long followedUserId,
			Date creationDate) {
		this.followerUserId = followerUserId;
		this.followedUserId = followedUserId;
		this.creationDate = creationDate;
	}

	public Long getFollowerUserId() {
		return this.followerUserId;
	}

	public void setFollowerUserId(Long followerUserId) {
		this.followerUserId = followerUserId;
	}

	public Long getFollowedUserId() {
		return this.followedUserId;
	}

	public void setFollowedUserId(Long followedUserId) {
		this.followedUserId = followedUserId;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Long getFollowshipId() {
		return followshipId;
	}

	public void setFollowshipId(Long followshipId) {
		this.followshipId = followshipId;
	}

}
