package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1


/**
 * Hashtag generated by hbm2java
 */
public class Hashtag implements java.io.Serializable {

	private Integer hashTagId;
	private Integer bookId;
	private String tag;
	private Integer bookAdderId;
	private int bookBookId;

	public Hashtag() {
	}

	public Hashtag(int bookBookId) {
		this.bookBookId = bookBookId;
	}

	public Hashtag(Integer bookId, String tag, Integer bookAdderId,
			int bookBookId) {
		this.bookId = bookId;
		this.tag = tag;
		this.bookAdderId = bookAdderId;
		this.bookBookId = bookBookId;
	}

	public Integer getHashTagId() {
		return this.hashTagId;
	}

	public void setHashTagId(Integer hashTagId) {
		this.hashTagId = hashTagId;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Integer getBookAdderId() {
		return this.bookAdderId;
	}

	public void setBookAdderId(Integer bookAdderId) {
		this.bookAdderId = bookAdderId;
	}

	public int getBookBookId() {
		return this.bookBookId;
	}

	public void setBookBookId(int bookBookId) {
		this.bookBookId = bookBookId;
	}

}
