package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1


/**
 * UserId generated by hbm2java
 */
public class UserId implements java.io.Serializable {

	private int userId;
	private String userEmail;

	public UserId() {
	}

	public UserId(int userId, String userEmail) {
		this.userId = userId;
		this.userEmail = userEmail;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getUserEmail() == castOther.getUserEmail()) || (this
						.getUserEmail() != null
						&& castOther.getUserEmail() != null && this
						.getUserEmail().equals(castOther.getUserEmail())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		return result;
	}

}
