package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1


/**
 * Userroles generated by hbm2java
 */
public class Userroles implements java.io.Serializable {

	private Integer roleId;
	private Integer userId;
	private String roleName;

	public Userroles() {
	}

	public Userroles(Integer userId, String roleName) {
		this.userId = userId;
		this.roleName = roleName;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
