package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1


/**
 * Action generated by hbm2java
 */
public class Action implements java.io.Serializable {

	private ActionType actionType;
	private Integer userId;
	private Integer actionId;

	public Action() {
	}

	public Action(ActionType actionType, Integer userId) {
		this.actionType = actionType;
		this.userId = userId;
	}


	public ActionType getActionType() {
		return actionType;
	}

	public void setActionType(ActionType actionType) {
		this.actionType = actionType;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getActionId() {
		return this.actionId;
	}

	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

}
