package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer commentId;
	private Integer commenterId;
	private String commentText;
	private Integer commentedBookId;
	private Integer commentedBookAdderId;
	private Date creationDate;

	public Comment() {
	}

	public Comment(Integer commenterId, String commentText,
			Integer commentedBookId, Integer commentedBookAdderId,
			Date creationDate) {
		this.commenterId = commenterId;
		this.commentText = commentText;
		this.commentedBookId = commentedBookId;
		this.commentedBookAdderId = commentedBookAdderId;
		this.creationDate = creationDate;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public Integer getCommenterId() {
		return this.commenterId;
	}

	public void setCommenterId(Integer commenterId) {
		this.commenterId = commenterId;
	}

	public String getCommentText() {
		return this.commentText;
	}

	public void setCommentText(String commentText) {
		this.commentText = commentText;
	}

	public Integer getCommentedBookId() {
		return this.commentedBookId;
	}

	public void setCommentedBookId(Integer commentedBookId) {
		this.commentedBookId = commentedBookId;
	}

	public Integer getCommentedBookAdderId() {
		return this.commentedBookAdderId;
	}

	public void setCommentedBookAdderId(Integer commentedBookAdderId) {
		this.commentedBookAdderId = commentedBookAdderId;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
