package com.bookworm.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * FollowShip generated by hbm2java
 */
public class FollowShip implements java.io.Serializable {

	private FollowShipId id;

	public FollowShip() {
	}

	public FollowShip(FollowShipId id) {
		this.id = id;
	}

	public FollowShipId getId() {
		return this.id;
	}

	public void setId(FollowShipId id) {
		this.id = id;
	}

}
